### ISSUE TITLE
deploy pat as a cloudfoundry app

### ISSUE THREAD

**Issue by wsktflihc** [cloudfoundry-incubator/pat#102]
hello:
     When I deploy PAT as a app,It will cause a problem "Server error, status code: 400, error code: 170001, message: Staging error: cannot get instances since staging failed".I cat the staged logs,find out running the buildpack comile file to 'go get -tags cf ./...',It cause the problem above.
     When I run the command 'go get -tags cf ' locally follow the comiple file,It will cause problems like these 
./github.com/cloudfoundry-incubator/pat/workloads/gcf.go:41:    err := Cf("push", "pats-"+guid.String(), "-m", "64M", "-p", pathToApp).ExpectOutput("App started")
./github.com/cloudfoundry-incubator/pat/workloads/gcf.go:86:    err = Cf("push", "pats-"+guid.String(), "-m", "128M", "-p", dstDir).ExpectOutput("App started").
   thank you!

**Comment by wsktflihc** [comment]
I annotate the ".ExpectOutput("App started")" line 41 and line 86 in workloads/gcf.go,deploy pat as a app success in cf .

**Comment by jberkhahn** [comment]
Hello wsktflihc,

While we're hoping that PAT will eventually be able to be deployed as a Cloud Foundry app, it currently does not support it due to difficulties in using the cf cli from within a deployed app. For now, we recommend you try running it locally.
