### ISSUE TITLE
Using rest:push can not start  app 

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-incubator/pat#106]
Hello,
   When using rest:push to test the performance of restapi, the staging phase is completed,but can not startup. In gcf:push testing, we found that routes should be created and bound with app before put the bits to compile. How to deal with it ?

root@smm1205:/home/pat/src/github.com/cloudfoundry-incubator/pat# gcf apps
Getting apps in org DevBox / space test as admin...
OK
name                                   requested state   instances   memory   disk   urls  
dora                                   started           1/1         1G       1G     dora.9.91.5.24.xip.io  
967910ad-cbba-4ad2-5499-1c744fa0588e   started           0/1         1G       1G  
root@smm1205:/home/pat/src/github.com/cloudfoundry-incubator/pat#

**Comment by jberkhahn** [comment]
Hey there,

Right now the app pushed using rest push does have an error where it does not send the URL of the apps back to the client. This isn't a huge issue as currently we're only push a simple hello world app, so being able to access it isn't a huge issue.

However, if we were to implement pushing your own app, which i something we've been thinking of implementing, this would become a problem. Is this something you would be interested in seeing?
